//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::notification_preferences::Entity as NotificationPreferences;
pub use super::price_history::Entity as PriceHistory;
pub use super::products::Entity as Products;
