//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub product_id: i32,
    pub current_price: Decimal,
    pub highest_price: Decimal,
    pub lowest_price: Decimal,
    pub last_updated: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notification_preferences::Entity")]
    NotificationPreferences,
    #[sea_orm(has_many = "super::price_history::Entity")]
    PriceHistory,
}

impl Related<super::notification_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationPreferences.def()
    }
}

impl Related<super::price_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
